services:
  webtop:
    image: lscr.io/linuxserver/webtop:alpine-xfce
    container_name: webtop
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    shm_size: "2gb"
    ports:
      - "3000:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/
    volumes:
      - webtop-data:/config

volumes:
  webtop-data:
